
name: "Haskell Updates Status"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Update every 6 hours
    # - cron:  '0 */6 * * *'
    - cron:  '*/10 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: cachix/install-nix-action@v13
      #   with:
      #     nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/haskell-updates.tar.gz

      - run: |
          # Set GitHub Actions Bot email address and user name.
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git status

          git rev-parse HEAD

          cat .git/HEAD

          git diff

          pwd

          ls -la

          ls -la ..

          # Store the current

          # Create a branch to store the generated README.md file.


          # Generate the new README.md file.
          # ./update.sh
          # mv README.md
          # git commit -am "Automated report"
          # git push
          # ./update.sh
