
name: "Haskell Updates Status"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Update every 6 hours
    - cron:  '0 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/haskell-updates.tar.gz

      - run: ./update.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          # Make the author of the commits the github_actions bot.
          default_author: github_actions
          # Make sure to do a `git pull --rebase` before committing.
          # This makes it more likely for old workflows to succeed
          # if they are run again.
          pull_strategy: --rebase
