
name: "Haskell Updates Status"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Update every 6 hours
    # - cron:  '0 */6 * * *'
    - cron:  '*/10 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: cachix/install-nix-action@v13
      #   with:
      #     nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/haskell-updates.tar.gz

      - run: |
          # Set GitHub Actions Bot email address and user name.
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git status

          git rev-parse HEAD

          cat .git/HEAD

          git diff

          pwd

          ls -la

          ls -la ..

          commit=$(git rev-parse --short HEAD)

          # Create the updated README.md using the script from this checkout.
          ./update.sh
          mv README.md ../README.md-new

          # Checkout the remote main branch.
          git fetch
          git reset --hard origin/main
          mv ../README.md-new ./README.md
          git add README.md
          git commit -m "Updated README.md from update.sh at ${commit}"
          git push origin HEAD:main
